### ISSUE TITLE
try to apply wf-swarm Keycloak Integration

### ISSUE THREAD

**Issue by helio-frota** [aeshell/nanook#134]

**Comment by eprogramming** [comment]
@emag this will be awesome if we can get this working ( i have no idea how but no problem ) : ]

**Comment by emag** [comment]
Good! I tried Keycloak a bit before, it is a nice SSO server.

Anyway, do you have any plan to introduce authentication for nanook ?

**Comment by eprogramming** [comment]
@emag i have no idea for now, but since this project is a 'prototype no sure for production' : ]
maybe we can try something with file authentication first , i mean put some 'admin/admin' on a file and try to authenticate.

i don't know if  keycloak works with plain file btw but we can talk with folks of keycloak to ask about the simplest(?) way to do

**Comment by emag** [comment]
FWIW, Keycloak is an authentication(SSO) ***server***. In my opinion, it's over-engineered for only Nanook(though, of cource, it's interseting !)

[WildFly Security Realm](https://docs.jboss.org/author/display/WFLY9/Security+Realms) is more simple, especially for file base authentication.

**Comment by eprogramming** [comment]
got it , you right.
+1 for wf sec realm.

**Comment by helio-frota** [comment]
using undertowjs fraction of wildfly-swarm and jquery terminal for the front-end.
try just keep this integration working ^
